### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by alexavil** [InvidJS/InvidJS#2]
The module will be fully ready once the following checklist is completed:

- [x] Instance fetching (basic info and stats)
- [x] Video info fetching.
- [x] Playlist info fetching.
- [x] Mixes info fetching (should be similar to playlists).
- [x] Stream fetching and playback (must work in DoppelBot's testing build)
- [x] Search engine.
- [x] Documentation.
- [x] Tests.

**Comment by alexavil** [comment]
Mixes are glorified playlists and work with the default API.

**Comment by alexavil** [comment]
Mixes are glorified playlists and work with the default API.

**Comment by alexavil** [comment]
Search Engine notes: 
If searching for a movie, Invidious API returns a video. If searching for a show, the API returns a channel.
The types have been ported as is, because the results differ, but there are essentially only 3 types of objects the API can return.

**Comment by alexavil** [comment]
The first release of InvidJS will be shipped with DoppelBot's Anniversary Update.
